channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bwa=0.7.12
  - samtools=1.3.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - bioconductor-qdnaseq=1.10.0
  - picard=2.15.0
  - fastqc=0.11.5
  - ucsc-bigwigaverageoverbed
  - bioconductor-bsgenome
  - bioconductor-CGHregions
  - r-MASS
  - r-R.cache
  - r-gtools
  - r-survival
  - perl-bioperl
  - perl-dbd-mysql
