channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.8.5
  - bwa
  - samtools
  - snakemake=5.31
  - pyyaml
  - picard
  - fastqc
  - perl-bioperl
  - perl-dbd-mysql
  - bioconductor-qdnaseq.hg19
  - bioconductor-biobase
  - bioconductor-cghcall
  - bioconductor-cghregions
  - bioconductor-limma
  - bioconductor-impute
  - r-matrixstats
  - r-r.cache
  - r-denstrip
  - r-flexmix
  - r-gtools
  - r-mass
  - r-devtools
  - r-ggplot2
  - r-survival
